// AUTOGENERATED FROM PICO_CONFIG_HEADER_FILES and then PICO_<PLATFORM>_CONFIG_HEADER_FILES
// DO NOT EDIT!


// based on PICO_CONFIG_HEADER_FILES:

#include "/home/adam/Documents/git/develop/rp2040-ota-bootloader/lib/pico-sdk/src/boards/include/boards/waveshare_rp2040_zero.h"
#include "/home/adam/Documents/git/develop/rp2040-ota-bootloader/lib/pico-sdk/src/rp2_common/cmsis/include/cmsis/rename_exceptions.h"

// based on PICO_RP2040_CONFIG_HEADER_FILES:
